# Generated by Django 3.2.16 on 2022-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_persons', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booking_date_time_start', models.DateTimeField()),
                ('booking_date_time_end', models.DateTimeField()),
            ],
        ),
    ]
