# Generated by Django 3.2.16 on 2022-12-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_date_time_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_date_time_start',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
