# Generated by Django 3.2.16 on 2022-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20221208_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default='Placeholder', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Placeholder', max_length=100),
        ),
    ]
