# Generated by Django 3.2.16 on 2022-12-12 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='table',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='reservation.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 12, 9, 38, 26, 83286, tzinfo=utc), verbose_name='Start time'),
        ),
    ]
