# Generated by Django 3.2.16 on 2022-12-14 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20221212_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 14, 18, 42, 22, 380427, tzinfo=utc), verbose_name='Start time'),
        ),
    ]
