# Generated by Django 3.2.16 on 2022-12-16 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=10)),
                ('booking_time', models.CharField(choices=[('1', '15:00-17:00'), ('2', '16:00-18:00'), ('3', '17:00-19:00'), ('4', '18:00-20:00'), ('5', '19:00-21:00'), ('6', '20:00-22:00')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
