# Generated by Django 3.2.16 on 2022-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20221216_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TableBooking',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(related_name='reservations', to='reservation.Table'),
        ),
    ]
