# Generated by Django 3.2.16 on 2022-12-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
