# Generated by Django 3.2.16 on 2022-12-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_delete_tablebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
