# Generated by Django 3.2.18 on 2023-05-03 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_remove_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_persons',
            field=models.PositiveIntegerField(),
        ),
    ]
